/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedShiftsRouteImport } from './routes/_authenticated/shifts'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedEquipmentIndexRouteImport } from './routes/_authenticated/equipment.index'
import { Route as AuthenticatedShiftReportRouteImport } from './routes/_authenticated/shift.report'
import { Route as AuthenticatedShiftHandoverRouteImport } from './routes/_authenticated/shift.handover'
import { Route as AuthenticatedShiftChecklistRouteImport } from './routes/_authenticated/shift.checklist'
import { Route as AuthenticatedScheduleTasksRouteImport } from './routes/_authenticated/schedule_.tasks'
import { Route as AuthenticatedManagerReportsRouteImport } from './routes/_authenticated/manager.reports'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShiftsRoute = AuthenticatedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipmentIndexRoute =
  AuthenticatedEquipmentIndexRouteImport.update({
    id: '/equipment/',
    path: '/equipment/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShiftReportRoute =
  AuthenticatedShiftReportRouteImport.update({
    id: '/shift/report',
    path: '/shift/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShiftHandoverRoute =
  AuthenticatedShiftHandoverRouteImport.update({
    id: '/shift/handover',
    path: '/shift/handover',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShiftChecklistRoute =
  AuthenticatedShiftChecklistRouteImport.update({
    id: '/shift/checklist',
    path: '/shift/checklist',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScheduleTasksRoute =
  AuthenticatedScheduleTasksRouteImport.update({
    id: '/schedule_/tasks',
    path: '/schedule/tasks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManagerReportsRoute =
  AuthenticatedManagerReportsRouteImport.update({
    id: '/manager/reports',
    path: '/manager/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/manager/reports': typeof AuthenticatedManagerReportsRoute
  '/schedule/tasks': typeof AuthenticatedScheduleTasksRoute
  '/shift/checklist': typeof AuthenticatedShiftChecklistRoute
  '/shift/handover': typeof AuthenticatedShiftHandoverRoute
  '/shift/report': typeof AuthenticatedShiftReportRoute
  '/equipment/': typeof AuthenticatedEquipmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/manager/reports': typeof AuthenticatedManagerReportsRoute
  '/schedule/tasks': typeof AuthenticatedScheduleTasksRoute
  '/shift/checklist': typeof AuthenticatedShiftChecklistRoute
  '/shift/handover': typeof AuthenticatedShiftHandoverRoute
  '/shift/report': typeof AuthenticatedShiftReportRoute
  '/equipment': typeof AuthenticatedEquipmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/shifts': typeof AuthenticatedShiftsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/manager/reports': typeof AuthenticatedManagerReportsRoute
  '/_authenticated/schedule_/tasks': typeof AuthenticatedScheduleTasksRoute
  '/_authenticated/shift/checklist': typeof AuthenticatedShiftChecklistRoute
  '/_authenticated/shift/handover': typeof AuthenticatedShiftHandoverRoute
  '/_authenticated/shift/report': typeof AuthenticatedShiftReportRoute
  '/_authenticated/equipment/': typeof AuthenticatedEquipmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/change-password'
    | '/dashboard'
    | '/schedule'
    | '/shifts'
    | '/team'
    | '/manager/reports'
    | '/schedule/tasks'
    | '/shift/checklist'
    | '/shift/handover'
    | '/shift/report'
    | '/equipment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/change-password'
    | '/dashboard'
    | '/schedule'
    | '/shifts'
    | '/team'
    | '/manager/reports'
    | '/schedule/tasks'
    | '/shift/checklist'
    | '/shift/handover'
    | '/shift/report'
    | '/equipment'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/change-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/schedule'
    | '/_authenticated/shifts'
    | '/_authenticated/team'
    | '/_authenticated/manager/reports'
    | '/_authenticated/schedule_/tasks'
    | '/_authenticated/shift/checklist'
    | '/_authenticated/shift/handover'
    | '/_authenticated/shift/report'
    | '/_authenticated/equipment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shifts': {
      id: '/_authenticated/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthenticatedShiftsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment/': {
      id: '/_authenticated/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof AuthenticatedEquipmentIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shift/report': {
      id: '/_authenticated/shift/report'
      path: '/shift/report'
      fullPath: '/shift/report'
      preLoaderRoute: typeof AuthenticatedShiftReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shift/handover': {
      id: '/_authenticated/shift/handover'
      path: '/shift/handover'
      fullPath: '/shift/handover'
      preLoaderRoute: typeof AuthenticatedShiftHandoverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shift/checklist': {
      id: '/_authenticated/shift/checklist'
      path: '/shift/checklist'
      fullPath: '/shift/checklist'
      preLoaderRoute: typeof AuthenticatedShiftChecklistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule_/tasks': {
      id: '/_authenticated/schedule_/tasks'
      path: '/schedule/tasks'
      fullPath: '/schedule/tasks'
      preLoaderRoute: typeof AuthenticatedScheduleTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/reports': {
      id: '/_authenticated/manager/reports'
      path: '/manager/reports'
      fullPath: '/manager/reports'
      preLoaderRoute: typeof AuthenticatedManagerReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedShiftsRoute: typeof AuthenticatedShiftsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedManagerReportsRoute: typeof AuthenticatedManagerReportsRoute
  AuthenticatedScheduleTasksRoute: typeof AuthenticatedScheduleTasksRoute
  AuthenticatedShiftChecklistRoute: typeof AuthenticatedShiftChecklistRoute
  AuthenticatedShiftHandoverRoute: typeof AuthenticatedShiftHandoverRoute
  AuthenticatedShiftReportRoute: typeof AuthenticatedShiftReportRoute
  AuthenticatedEquipmentIndexRoute: typeof AuthenticatedEquipmentIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedShiftsRoute: AuthenticatedShiftsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedManagerReportsRoute: AuthenticatedManagerReportsRoute,
  AuthenticatedScheduleTasksRoute: AuthenticatedScheduleTasksRoute,
  AuthenticatedShiftChecklistRoute: AuthenticatedShiftChecklistRoute,
  AuthenticatedShiftHandoverRoute: AuthenticatedShiftHandoverRoute,
  AuthenticatedShiftReportRoute: AuthenticatedShiftReportRoute,
  AuthenticatedEquipmentIndexRoute: AuthenticatedEquipmentIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
